### ISSUE TITLE
Real birthdate

### ISSUE THREAD

**Issue by briandiaz** [adamcooke/fake-person#2]
Hi

It would be nice, for testing and real process of the app, that the person instance have a age with at least the correspondent birthyear.

For example:
person.date_of_birth              #=> #<Date: 1954-10-12>
person.age                             #=> 37

Should be
person.date_of_birth              #=> #<Date: 1978-10-12>
person.age                            #=> 37

Thanks.

**Comment by adamcooke** [comment]
A person's age will always be the correct age based on the date of birth. See [here](https://github.com/adamcooke/fake-person/blob/master/lib/fake_person/date_of_birth.rb)

**Comment by briandiaz** [comment]
Thanks didn't notice that.
Issue can be closed.
